on:
  push:
    branches:
      - master

name: Build

jobs:
  build:
    name: Matrix build 
    runs-on: ${{ matrix.os }} 
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name:
      run: npm ci && npm run make
