on:
  push:
    branches:
      - master

name: Build

jobs:
  create-release:
    name: Create release
    runs-on: ubuntu-latest
    steps:
      - name: Create tag
        id: create_tag
        run: |
          tag=builds-$(date +%Y%m%d-%H%M%S)
          echo "::set-output name=tag::$tag"
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.create_tag.outputs.tag }}
          release_name: ${{ steps.create_tag.outputs.tag }}
          draft: true
          prerelease: false
  build:
    name: Matrix build 
    needs: create-release
    runs-on: ${{ matrix.os }} 
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name:
        run: npm ci && npm run make
